### ISSUE TITLE
Hutao也姓H，Hongdui也姓H；Hutao也会嗷，saomiao也会ao

### ISSUE THREAD

**Issue by BronyeZaychik** [shimmeris/shimmeris.github.io#1]
虚假的蓝队：头像是火属性的Futao
真正的蓝队：甘雨天下第一！

**Comment by shimmeris** [comment]
hhh太生艹了。
你们看到我的 ip 是因为我反制那台肉鸡，弹了个 shell 到这台我都忘了有域名的 vps 了，溯我木得用的🦆。
另外原来你也玩原神.jpg

**Comment by BronyeZaychik** [comment]
大丘丘病了二丘丘瞧
三丘丘看到二丘丘描
另外玩啥原神，当然是淦翻原神，崩坏永存！

**Comment by shimmeris** [comment]
崩坏策划鬼才

**Comment by BronyeZaychik** [comment]
崩坏音乐美工nb！

**Comment by shimmeris** [comment]
啊这

**Comment by BronyeZaychik** [comment]
看来都是老二次元了，轻音少女好评

**Comment by shimmeris** [comment]
<img width="83" alt="Screen Shot 2021-04-02 at 9 33 24 AM" src="https://user-images.githubusercontent.com/17252049/114679059-69977980-9d3e-11eb-99fd-97c3064a6f6e.png">

**Comment by BronyeZaychik** [comment]
太感动了，居然没有加料555！
